defaults: &defaults
 
:development:
  :couchdb:
    :url: http://localhost:5984/class_axis_development
  <<: *defaults
  
:test:
  :couchdb:
    :url: http://localhost:5984/class_axis_test
    <<: *defaults

:production:
  :couchdb:
    :url: http://localhost:5984/class_axis_production
    <<: *defaults